# Generated by Django 3.0 on 2019-12-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('msg', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Maildata',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('indate', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('sender', models.CharField(max_length=100)),
                ('recipient', models.CharField(max_length=100)),
                ('datedb', models.DateTimeField()),
                ('checkdb', models.IntegerField()),
            ],
            options={
                'db_table': 'maildata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('mailaddress', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'userinfo',
                'managed': False,
            },
        ),
    ]
