# Generated by Django 3.0.1 on 2020-01-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailweb', '0002_remote_retmoeuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteLocal',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('user_ip', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('user_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'remote_local',
                'managed': False,
            },
        ),
    ]
